### ISSUE TITLE
Limit available tech

### ISSUE THREAD

**Issue by popiel** [aandergr/kspalculator#17]
The calculator reports what the tech requirements are for a given build, but there's no way to prevent it from suggesting use of advanced tech.  For early- and mid-game, it would be nice to be able to specify which tech you actually have available, and only get builds using that tech.

**Comment by aandergr** [comment]
It may suggest designs with high tech requirements, however since it shows all best designs, and the `Design.is_better_than()` method also considers the Design's tech requirements with `NodeSet.is_easier_than()`, alternative designs that have worse cost but lower technology requirements should be also suggested by kspalculator. I think since there are usually few designs suggested, it is not necessary to further filter the list.

**Comment by popiel** [comment]
You're right, this is redundant and unnecessary.
